In [64]:
# %pip install --upgrade pandas

In [65]:
import pandas as pd
import numpy as np

# Reading files (.csv, .xlsx)

In [66]:
# Read a CSV file into a DataFrame
df = pd.read_csv("./data/googleplaystore.csv")

# Let's take a look what "df" is
# Notice, how you can combine f-strings and python variables
# Finished early? Take a few minutes to expore f-strings in detail! https://www.datacamp.com/tutorial/f-string-formatting-in-python?
print(f"Pandas library saved data into {type(df)} type of object.")
print("\n")

# Display the first 5 rows of the DataFrame
df.head()
#df.shape

Pandas library saved data into <class 'pandas.core.frame.DataFrame'> type of object.

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [67]:
# Display the first 10 rows of the DataFrame
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [68]:
#df2 = pd.read_excel("data/googleplaystore.xlsx")
#TODO list first 20 rows!
df.head(20)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
10,Text on Photo - Fonteee,ART_AND_DESIGN,4.4,13880,28M,"1,000,000+",Free,0,Everyone,Art & Design,"October 27, 2017",1.0.4,4.1 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.4,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.0.15,4.0 and up
12,Tattoo Name On My Photo Editor,ART_AND_DESIGN,4.2,44829,20M,"10,000,000+",Free,0,Teen,Art & Design,"April 2, 2018",3.8,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,"June 6, 2018",NaN,4.2 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
18,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216,39M,"5,000,000+",Free,0,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up

# Basic DataFrame Exploration:

In [69]:
#View the last few rows of a DataFrame.
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [70]:
#TODO Use .info() fuction to get information about the DataFrame, including data types and missing values.
#str, int and bool will be of type object 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [71]:
#Generate summary statistics for numerical columns.
df.describe() #stats for every numerical column in the table
#count = number of rows

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [72]:
#Get the number of rows and columns in the DataFrame.
df.shape

(10841, 13)

In [73]:
#TODO use .columns attribute to access column names of the DataFrame.
df.columns #gets index object for the column

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [74]:
#Access the row labels of the DataFrame.
df.index

RangeIndex(start=0, stop=10841, step=1)

In [75]:
#Access the row label values of the DataFrame.
df.index.values #output --> array([    0,     1,     2, ..., 10838, 10839, 10840], dtype=int64)

array([    0,     1,     2, ..., 10838, 10839, 10840], dtype=int64)

In [76]:
#show random sample oof df using .sample() function

#gets random samples from the dataframe - rows!

df.sample(5) #specify numbers of random rows you need

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
6666,Left vs Right: Brain Training,FAMILY,4.5,75719,30M,"5,000,000+",Free,0,Everyone,Educational,"November 24, 2017",3.3.0,4.0.3 and up
4032,Dubsmash,VIDEO_PLAYERS,4.2,1971777,29M,"100,000,000+",Free,0,Teen,Video Players & Editors,"May 11, 2018",2.35.8,4.1 and up
7131,C B Patel Health Club,HEALTH_AND_FITNESS,5.0,5,14M,100+,Free,0,Everyone,Health & Fitness,"July 2, 2018",1.0.1,4.4 and up
1760,Kick the Buddy,GAME,4.3,1000417,Varies with device,"50,000,000+",Free,0,Teen,Action,"July 5, 2018",Varies with device,4.4 and up
9498,EK Bailey Preaching Conference,EVENTS,5.0,3,30M,500+,Free,0,Everyone,Events,"July 2, 2018",5.30.01,5.1 and up

In [77]:
#access column
df["Genres"] #returns a series object

0                     Art & Design
1        Art & Design;Pretend Play
2                     Art & Design
3                     Art & Design
4          Art & Design;Creativity
                   ...
10836                    Education
10837                    Education
10838                      Medical
10839            Books & Reference
10840                    Lifestyle
Name: Genres, Length: 10841, dtype: object

In [78]:
#or same result differenty syntax
df.Genres

0                     Art & Design
1        Art & Design;Pretend Play
2                     Art & Design
3                     Art & Design
4          Art & Design;Creativity
                   ...
10836                    Education
10837                    Education
10838                      Medical
10839            Books & Reference
10840                    Lifestyle
Name: Genres, Length: 10841, dtype: object

In [79]:
#access a row with index = 4
df.iloc[10] #gets row number 4 but all its corresponding column names as the rows and a singular column series

App               Text on Photo - Fonteee
Category                   ART_AND_DESIGN
Rating                                4.4
Reviews                             13880
Size                                  28M
Installs                       1,000,000+
Type                                 Free
Price                                   0
Content Rating                   Everyone
Genres                       Art & Design
Last Updated             October 27, 2017
Current Ver                         1.0.4
Android Ver                    4.1 and up
Name: 10, dtype: object

In [80]:
#TODO access Column Price from a row with index = 10

df.Price[10]

#or 
df.iloc[4]['Price'] 
df.iloc[10].Price
df.Price.iloc[10]

'0'

In [81]:
#Column Generes is pandas Series object
print(type(df.Genres))

<class 'pandas.core.series.Series'>

In [82]:
#however you can transform it e.g. to list with to_list() python method
df.Genres.to_list() #or list(df.Genres)

['Art & Design',
 'Art & Design;Pretend Play',
 'Art & Design',
 'Art & Design',
 'Art & Design;Creativity',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design;Creativity',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design;Action & Adventure',
 'Art & Design',
 'Art & Design',
 'Art & Design;Creativity',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design;Creativity',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design;Creativity',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Art & Design',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Auto & Vehicles',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Beauty',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Books & Reference',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics;Creativity',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Comics',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Dating',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Creativity',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Creativity',
 'Education;Education',
 'Education',
 'Education;Music & Video',
 'Education;Education',
 'Education;Creativity',
 'Education',
 'Education',
 'Education;Action & Adventure',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Pretend Play',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Brain Games',
 'Education',
 'Education;Brain Games',
 'Education;Brain Games',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education',
 'Education',
 'Education;Education',
 'Education',
 'Education;Education',
 'Education',
 'Education;Pretend Play',
 'Education;Education',
 'Education;Pretend Play',
 'Education;Pretend Play',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Brain Games',
 'Entertainment',
 'Entertainment',
 'Entertainment;Brain Games',
 'Entertainment',
 'Entertainment',
 'Entertainment;Creativity',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment;Music & Video',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 'Entertainment',
 ...]

In [83]:
#or we can use numpy array output
df.Genres.values

array(['Art & Design', 'Art & Design;Pretend Play', 'Art & Design', ...,
       'Medical', 'Books & Reference', 'Lifestyle'], dtype=object)

In [84]:
#let's see how many unique Genres there are in the df
# brute force approach using basic python knowledge would allow us to do

genre_list = df.Genres.to_list()
genre_set = set(genre_list) #gives only unique values
print(genre_set)
print(f"There are {len(genre_set)} unique genres in the dataframe")

{'Education;Music & Video', 'Entertainment;Creativity', 'Personalization', 'Parenting;Brain Games', 'Weather', 'Puzzle;Brain Games', 'Casual;Pretend Play', 'Card;Action & Adventure', 'Board;Pretend Play', 'Health & Fitness;Education', 'Health & Fitness;Action & Adventure', 'Strategy;Education', 'Strategy;Creativity', 'Comics;Creativity', 'Events', 'Educational;Education', 'Card;Brain Games', 'Casual;Brain Games', 'Educational;Action & Adventure', 'Social', 'Beauty', 'Travel & Local', 'Art & Design;Creativity', 'Board;Action & Adventure', 'Simulation;Action & Adventure', 'Puzzle', 'Auto & Vehicles', 'Entertainment;Music & Video', 'Video Players & Editors;Music & Video', 'Medical', 'Productivity', 'Puzzle;Education', 'Communication;Creativity', 'Education;Pretend Play', 'Simulation', 'Tools', 'Arcade;Action & Adventure', 'Entertainment;Education', 'Video Players & Editors', 'Art & Design', 'Travel & Local;Action & Adventure', 'Casino', 'Role Playing;Education', 'Role Playing;Action & Adventure', 'Casual;Education', 'Board', 'Books & Reference', 'Communication', 'Sports', 'Lifestyle;Education', 'Books & Reference;Education', 'Art & Design;Action & Adventure', 'Educational;Brain Games', 'Trivia', 'Music;Music & Video', 'Action;Action & Adventure', 'Maps & Navigation', 'February 11, 2018', 'Racing;Action & Adventure', 'Educational', 'Parenting;Education', 'Education;Creativity', 'Educational;Pretend Play', 'Parenting;Music & Video', 'Food & Drink', 'House & Home', 'Puzzle;Creativity', 'Finance', 'Sports;Action & Adventure', 'Simulation;Pretend Play', 'Action', 'Board;Brain Games', 'Music & Audio;Music & Video', 'Strategy', 'Dating', 'Puzzle;Action & Adventure', 'Education;Education', 'Card', 'Education;Brain Games', 'Strategy;Action & Adventure', 'Lifestyle;Pretend Play', 'Video Players & Editors;Creativity', 'Adventure;Brain Games', 'Education', 'Adventure', 'Casual;Creativity', 'Arcade', 'Parenting', 'Health & Fitness', 'Adventure;Action & Adventure', 'Photography', 'Lifestyle', 'Entertainment;Brain Games', 'Casual', 'Art & Design;Pretend Play', 'Music', 'Educational;Creativity', 'Libraries & Demo', 'Role Playing;Brain Games', 'Role Playing', 'Word', 'Arcade;Pretend Play', 'Trivia;Education', 'Casual;Music & Video', 'Comics', 'Books & Reference;Creativity', 'Tools;Education', 'Education;Action & Adventure', 'Racing;Pretend Play', 'Simulation;Education', 'Role Playing;Pretend Play', 'Entertainment;Action & Adventure', 'Adventure;Education', 'Entertainment;Pretend Play', 'Entertainment', 'Shopping', 'Casual;Action & Adventure', 'Business', 'Racing', 'News & Magazines'}
There are 120 unique genres in the dataframe

In [85]:
#more elegant way is to be aware of basic pandas methods and use them

#TODO use  method .unique() display all unique Generes in dataset

df.Genres.unique()

#TODO use  method .nunique() count all unique Generes in datasets
df.Genres.nunique()

120

# Conditions and filtering

In [86]:
#let's write a condition
df.Genres == "Word"

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Genres, Length: 10841, dtype: bool

In [87]:
#let's write or condition
(df.Genres == "Word") | (df.Genres == "Lifestyle")

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840     True
Name: Genres, Length: 10841, dtype: bool

In [88]:
#same result can be achieved from
df.Genres.isin(["Word", "Lifestyle"]) #alternative only for or condition

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840     True
Name: Genres, Length: 10841, dtype: bool

In [89]:
#let's write and condition
(df.Genres == "Word") & (df.Genres == "Lifestyle")

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Genres, Length: 10841, dtype: bool

In [90]:
#let's select rows where condition is true
condition = (df.Genres == "Word") | (df.Genres == "Lifestyle")
df[condition]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1562,Dollhouse Decorating Games,LIFESTYLE,4.1,18968,32M,"5,000,000+",Free,0,Teen,Lifestyle,"April 26, 2018",5.1,4.1 and up
1563,metroZONE,LIFESTYLE,4.1,47497,34M,"10,000,000+",Free,0,Everyone,Lifestyle,"June 8, 2018",5.3.0.54.7,5.0 and up
1564,Easy Hair Style Design,LIFESTYLE,4.3,601,5.1M,"100,000+",Free,0,Everyone,Lifestyle,"December 20, 2017",1.0,2.3 and up
1566,"Black Wallpaper, AMOLED, Dark Background: Darkify",LIFESTYLE,4.6,51357,80M,"5,000,000+",Free,0,Everyone,Lifestyle,"July 31, 2018",8.0,4.0 and up
1567,Girly Wallpapers Backgrounds,LIFESTYLE,4.4,13565,3.3M,"1,000,000+",Free,0,Everyone,Lifestyle,"August 5, 2018",2.5,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10791,Winter Wonderland,GAME,4.0,1287,38M,"50,000+",Free,0,Everyone,Word,"December 18, 2013",1.0,2.2 and up
10797,Fuel Rewards® program,LIFESTYLE,4.6,32433,46M,"1,000,000+",Free,0,Everyone,Lifestyle,"June 26, 2018",2.9.1,5.0 and up
10805,Scoreboard FR,LIFESTYLE,4.3,3,15M,100+,Free,0,Everyone,Lifestyle,"August 7, 2018",2.1,4.2 and up
10808,lesparticuliers.fr,LIFESTYLE,NaN,96,1.0M,"50,000+",Free,0,Everyone,Lifestyle,"November 25, 2014",1.5,2.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [91]:
#let's select rows where condition is not true
condition = (df.Genres == "Word") | (df.Genres == "Lifestyle")
df[~condition]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

In [92]:
#TODO select data where Category is FAMILY and Genres is Education 

new_condn = (df["Category"] == "FAMILY") & (df["Genres"] == "Education")
df[new_condn]

#or (df.Category == "FAMILY") & (df["Genres"]=="Education")


#TODO we explored, how .isin() method is used. Explore method .isna() to find out which rows have nan values
bla = df.isna()

#TODO sum, how many rows containing nan we have in the data 
#sum will give you the number of rows since True is 1 and false is 0

bla.sum() #applies sum to each column
#or df.isna.sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

# Joining and merging

In [93]:
df2 = {"Content Rating":['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+', 'Adults only 18+', 'Unrated', np.nan],
 "Restriction":["No", "No", "Yes", "Yes","Yes", "N/A", "N/A"]}
df2 = pd.DataFrame(df2)

# Merge two DataFrames by a common column
print(len(df))
merged_df = pd.merge(df, df2, on='Content Rating') #creates a new df with an extra column - no.of rows wont change
print(len(merged_df))
print(merged_df[["Content Rating", "Restriction"]].isna().sum()) #find rows that have Nans in content rating and restriction columns

10841
10841
Content Rating    1
Restriction       0
dtype: int64

In [94]:
merged_df[merged_df["Content Rating"].isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Restriction
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,N/A

In [95]:
df2 = {"Content Rating":['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+', 'Adults only 18+', 'Unrated'],
 "Restriction":["No", "No", "Yes", "Yes","Yes", "N/A"]}
df2 = pd.DataFrame(df2)

# Merge with different types of joins (e.g., inner, outer, left, right)
merged_df = pd.merge(df, df2, on='Content Rating', how='inner')

print(len(df))
print(len(merged_df))

10841
10840

In [96]:
pd.concat([df, df2], axis=0) #concat by rows - top to bottom

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Restriction
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,NaN
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,NaN
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Teen,NaN,NaN,NaN,NaN,No
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Everyone 10+,NaN,NaN,NaN,NaN,Yes
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mature 17+,NaN,NaN,NaN,NaN,Yes
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adults only 18+,NaN,NaN,NaN,NaN,Yes
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unrated,NaN,NaN,NaN,NaN,N/A

In [97]:
pd.concat([df, df2], axis=1) #concat by columns - side to side

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Content Rating,Restriction
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,Everyone,No
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,Teen,No
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,Everyone 10+,Yes
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Mature 17+,Yes
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,Adults only 18+,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,NaN,NaN
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,NaN,NaN
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,NaN,NaN
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,NaN,NaN
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,NaN,NaN

# Transforming columns

In [98]:
def multiply_twice(x):
    return x * 2

df['new_rating_var1'] = df['Rating'].apply(multiply_twice) #passing the function as a reference
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,new_rating_var1
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,8.2
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,7.8
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,9.4
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,9.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,8.6

In [99]:
# Apply a lambda function to a column
# lambda is a way for defining the anonymous function
df['new_rating_var2'] = df['Rating'].apply(lambda x: x * 2)


# Using lambda with conditionals
df['rating_conditional'] = df['Rating'].apply(lambda x: x * 2 if x > 1 else x)

In [116]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,new_rating_var1,new_rating_var2,rating_conditional
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,8.2,8.2,8.2
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,7.8,7.8,7.8
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,9.4,9.4,9.4
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,9.0,9.0,9.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,8.6,8.6,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,9.0,9.0,9.0
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,10.0,10.0,10.0
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,NaN,NaN,NaN
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,9.0,9.0,9.0
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,9.0,9.0,9.0

In [100]:
df[df.Rating <= 1].head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,new_rating_var1,new_rating_var2,rating_conditional
625,House party - live chat,DATING,1.0,1,9.2M,10+,Free,0,Mature 17+,Dating,"July 31, 2018",3.52,4.0.3 and up,2.0,2.0,1.0
4127,Speech Therapy: F,FAMILY,1.0,1,16M,10+,Paid,$2.99,Everyone,Education,"October 7, 2016",1.0,2.3.3 and up,2.0,2.0,1.0
5151,Clarksburg AH,MEDICAL,1.0,1,28M,50+,Free,0,Everyone,Medical,"May 1, 2017",300000.0.81,4.0.3 and up,2.0,2.0,1.0
5978,Truck Driving Test Class 3 BC,FAMILY,1.0,1,2.0M,50+,Paid,$1.49,Everyone,Education,"April 9, 2012",1.0,2.1 and up,2.0,2.0,1.0
6319,BJ Bridge Standard American 2018,GAME,1.0,1,4.9M,"1,000+",Free,0,Everyone,Card,"May 21, 2018",6.2-sayc,4.0 and up,2.0,2.0,1.0
6490,MbH BM,MEDICAL,1.0,1,2.3M,100+,Free,0,Everyone,Medical,"December 14, 2016",1.1.3,4.3 and up,2.0,2.0,1.0
7144,CB Mobile Biz,FINANCE,1.0,3,8.4M,500+,Free,0,Everyone,Finance,"February 22, 2016",4.4.1255,4.0 and up,2.0,2.0,1.0
7383,Thistletown CI,PRODUCTIVITY,1.0,1,6.6M,100+,Free,0,Everyone,Productivity,"March 15, 2018",41.9,4.1 and up,2.0,2.0,1.0
7427,CJ DVD Rentals,COMMUNICATION,1.0,5,13M,100+,Free,0,Everyone,Communication,"October 6, 2017",1.0,4.1 and up,2.0,2.0,1.0
7806,CR Magazine,BUSINESS,1.0,1,7.8M,100+,Free,0,Everyone,Business,"July 23, 2014",2.4.2,2.3.3 and up,2.0,2.0,1.0

# Aggregating dataframe

In [101]:
# Calculate mean, sum, and other aggregate functions
mean_value = df['Rating'].mean()
sum_value = df['Rating'].sum()

print(mean_value, sum_value)

# Group by a column and apply aggregation functions
grouped_df = df.groupby('Content Rating')['Rating'].agg(['mean', 'sum', 'count'])
grouped_df

4.193338315362443 39279.0

                     mean      sum  count
Content Rating
Adults only 18+  4.300000     12.9      3
Everyone         4.186375  31062.9   7420
Everyone 10+     4.257179   1690.1    397
Mature 17+       4.123427   1900.9    461
Teen             4.233487   4589.1   1084
Unrated          4.100000      4.1      1

In [102]:
# TODO use as_index =  False parameter in group by function to not use Content Rating as index
# grouped_df_new = df.groupby('Content Rating', as_index=False)['Rating']
# print(grouped_df_new)

# perform the grouping by multiple columns e.g. Content Rating and Type

grouped_df_new = df.groupby(['Content Rating', 'Type'], as_index = False)['Rating'].agg(['mean', 'sum', 'count'])
grouped_df_new

#if as_index is false, then the indices are just numbers and content rating or type is not used as the index

    Content Rating  Type      mean      sum  count
0  Adults only 18+  Free  4.300000     12.9      3
1         Everyone  Free  4.181712  28720.0   6868
2         Everyone  Paid  4.244384   2342.9    552
3     Everyone 10+  Free  4.251099   1547.4    364
4     Everyone 10+  Paid  4.324242    142.7     33
5       Mature 17+  Free  4.111937   1825.7    444
6       Mature 17+  Paid  4.423529     75.2     17
7             Teen  Free  4.224639   4389.4   1039
8             Teen  Paid  4.437778    199.7     45
9          Unrated  Free  4.100000      4.1      1

In [103]:

# Pivot table for aggregation
pivot_table = df.pivot_table(index='Content Rating', columns='Type', values='Price', aggfunc='sum')
pivot_table

Type,Free,Paid
Content Rating,,
Adults only 18+,000,NaN
Everyone,0000000000000000000000000000000000000000000000...,$4.99$4.99$4.99$4.99$3.99$6.99$2.99$3.99$5.99$...
Everyone 10+,0000000000000000000000000000000000000000000000...,$1.99$6.99$2.99$10.00$9.99$10.00$17.99$6.99$2....
Mature 17+,0000000000000000000000000000000000000000000000...,$3.99$7.99$3.99$2.99$11.99$11.99$0.99$1.99$3.9...
Teen,0000000000000000000000000000000000000000000000...,$1.49$3.99$4.99$6.99$9.99$2.99$1.99$4.99$0.99$...
Unrated,00,NaN

In [104]:
#Price should be float!
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   App                 10841 non-null  object
 1   Category            10841 non-null  object
 2   Rating              9367 non-null   float64
 3   Reviews             10841 non-null  object
 4   Size                10841 non-null  object
 5   Installs            10841 non-null  object
 6   Type                10840 non-null  object
 7   Price               10841 non-null  object
 8   Content Rating      10840 non-null  object
 9   Genres              10841 non-null  object
 10  Last Updated        10841 non-null  object
 11  Current Ver         10833 non-null  object
 12  Android Ver         10838 non-null  object
 13  new_rating_var1     9367 non-null   float64
 14  new_rating_var2     9367 non-null   float64
 15  rating_conditional  9367 non-null   float64
dtypes: float64(4), object(12)
memory usage: 1.3+ MB

In [105]:
df.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [106]:
#This is messy,  first lets get rid of dollar sign
df["Price"] = df["Price"].str.replace('$', '')  #overwriting the df
df.Price.unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       'Everyone', '1.20', '1.04'], dtype=object)

In [107]:
df[df.Price=="Everyone"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,new_rating_var1,new_rating_var2,rating_conditional
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,38.0,38.0,38.0

In [108]:
#The roow suggest its free
df["Price"] = df["Price"].str.replace('Everyone', '0')

In [109]:
#change data types using function .astype()
convert_dict = {'Price': float}
df = df.astype(convert_dict, ) #takes only tuples as an arguement hence (x, )

#alternate solution 
#df.Price.astype(float)

# dummy = float(df["Price"])
# dummy #TypeError: cannot convert the series to <class 'float'>

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   App                 10841 non-null  object
 1   Category            10841 non-null  object
 2   Rating              9367 non-null   float64
 3   Reviews             10841 non-null  object
 4   Size                10841 non-null  object
 5   Installs            10841 non-null  object
 6   Type                10840 non-null  object
 7   Price               10841 non-null  float64
 8   Content Rating      10840 non-null  object
 9   Genres              10841 non-null  object
 10  Last Updated        10841 non-null  object
 11  Current Ver         10833 non-null  object
 12  Android Ver         10838 non-null  object
 13  new_rating_var1     9367 non-null   float64
 14  new_rating_var2     9367 non-null   float64
 15  rating_conditional  9367 non-null   float64
dtypes: float64(5), object(11)
memory usage: 1.3+ MB

In [111]:
# Pivot table for aggregation
pivot_table = df.pivot_table(index='Content Rating', columns='Type', values='Price', aggfunc='sum')
pivot_table

Type             Free      Paid
Content Rating
Adults only 18+   0.0       NaN
Everyone          0.0  10205.60
Everyone 10+      0.0    156.69
Mature 17+        0.0    118.10
Teen              0.0    656.28
Unrated           0.0       NaN

In [112]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,new_rating_var1,new_rating_var2,rating_conditional
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,8.2,8.2,8.2
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,7.8,7.8,7.8
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,9.4,9.4,9.4
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,9.0,9.0,9.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,8.6,8.6,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,9.0,9.0,9.0
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,10.0,10.0,10.0
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,NaN,NaN,NaN
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,9.0,9.0,9.0
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,9.0,9.0,9.0

In [113]:
#TODO use pandas .melt() to unpivot table, use documentation to find out, which arguments you need to provide
dummy = pivot_table.reset_index().melt(id_vars= 'Content Rating', value_vars=pivot_table.columns, var_name= "Type", value_name="Price")

dummy

# dummy2 = pd.melt(pivot_table)
# dummy2

#collapses a df into smth that contains only two columns : variable and value - which column is a variable and which one is a value can be chosen

     Content Rating  Type     Price
0   Adults only 18+  Free      0.00
1          Everyone  Free      0.00
2      Everyone 10+  Free      0.00
3        Mature 17+  Free      0.00
4              Teen  Free      0.00
5           Unrated  Free      0.00
6   Adults only 18+  Paid       NaN
7          Everyone  Paid  10205.60
8      Everyone 10+  Paid    156.69
9        Mature 17+  Paid    118.10
10             Teen  Paid    656.28
11          Unrated  Paid       NaN

In [114]:
# %pip install  openpyxl

In [115]:
#TODO export pivot_table to exel using to_excel() function
dummy.to_excel("delete_later.xlsx", sheet_name='sheetname1')

#TODO use reset_index to change Type in pivot_table from index to column
new_table = pivot_table.reset_index()
new_table

Type   Content Rating  Free      Paid
0     Adults only 18+   0.0       NaN
1            Everyone   0.0  10205.60
2        Everyone 10+   0.0    156.69
3          Mature 17+   0.0    118.10
4                Teen   0.0    656.28
5             Unrated   0.0       NaN